import { Button, VerticalBox } from "std-widgets.slint";
import { ClearButton } from "buttons/clear_button.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    callback clear-value();

    VerticalBox {
        Text {
            stroke-style: TextStrokeStyle.outside;
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }

        ClearButton {
            clear-value => {
                root.clear-value();
            }
        }
    }
}